export const SET_PLAYLIST = "SET_PLAYLIST";

export const GET_TRACKLIST = "GET_TRACKLIST";
export const GET_TRACK = "GET_TRACK";
export const SET_TRACK_LOADING = "SET_TRACK_LOADING";
export const SET_TRACKLIST_LOADING = "SET_TRACKLIST_LOADING";
